language: python
sudo: false  # faster
dist: trusty
python:
  - "3.5"

branches:
  except:
  - dev

# install dependencies
addons:
  apt:
    packages:
    - python3-pyside
    - python3-setuptools
    - pyside-tools
    - qt4-linguist-tools
    - dpkg-dev
    - debhelper
    - devscripts
    - fakeroot
    - cdbs

install: true

script:
  - debuild -uc -us  # it will call setup.py build
  - /usr/bin/python3 utils/tests.py  # system python is also 3.5

deploy:
  provider: releases
  api_key: ${github_api_token}
  file: "../hazama*.deb"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
